### ISSUE TITLE
Vulkan initialisation fails on Windows

### ISSUE THREAD

**Issue by StrayLightning** [StrayLightning/aeolius#2]
This is a placeholder for information on problems with the Vulkan renderer initialisation failing on Windows with "Unexpected result from vkCreateSwapchainKHR: validation failed EXT".  The initialisation succeeds on Linux.  I have only nVidia GPUs to test this on at the moment.  I suspect an issue around the way the code is using glfw-rs/GLFW/Vulkan to create and tie in the Windows surface causes the Vulkan validation layers to barf.  But from reading and rereading the Vulkan spec for VkSwapchainCreateInfoKHR I cannot see anything wrong.

D:> cargo run --bin aeolius -- --vulkan --debug
    Finished debug [unoptimized + debuginfo] target(s) in 0.0 secs
     Running `target\debug\aeolius.exe --vulkan --debug`
Requested instance layers ["VK_LAYER_LUNARG_standard_validation"]
Requested instance extensions ["VK_KHR_surface", "VK_KHR_win32_surface", "VK_EXT_debug_report"]
Requested device extensions ["VK_KHR_swapchain"]
Physical device count is 1
Physical device number 0 is GTX 980M
Chose physical device: 1
Queue family count is 2
Minimum and maximum image counts are 2 - 8
Format count is 2
Presentation mode count is 3
Available presentation mode: FIFO_KHR
Available presentation mode: FIFO_RELAXED_KHR
Available presentation mode: MAILBOX_KHR
Selected presentation mode is: FIFO_RELAXED_KHR
supportedUsageFlags:     00000000000000000000000010011111
usage:                   00000000000000000000000000010000
supportedTransforms:     00000000000000000000000000000001
transform:               00000000000000000000000000000001
supportedCompositeAlpha: 00000000000000000000000000000001
alpha:                   00000000000000000000000000000001
surface_format.format:                     44
surface_format.colorSpace:                 0
surface_capabilities.currentExtent.width:  1600
surface_capabilities.currentExtent.height: 900
Unexpected result from vkCreateSwapchainKHR: validation failed EXT
thread 'main' panicked at 'Vulkan API call failed', src\graphics\renderervk.rs:676
stack backtrace:
   0:     0x7ff774d89354 - std::sys::c::SleepConditionVariableSRW::hfb1a6cde8493e83d
   1:     0x7ff774d87773 - std::rt::lang_start::h538f8960e7644c80
   2:     0x7ff774d8813d - std::panicking::rust_panic_with_hook::hc303199e04562edf
   3:     0x7ff774b2f927 - std::panicking::begin_panic<&str>
                        at C:\bot\slave\stable-dist-rustc-win-msvc-64\build\src\libstd\panicking.rs:413
   4:     0x7ff774b60b43 - aeoliuslib::graphics::renderervk::RendererVk::create_swapchain
                        at D:\keep\hg\programs\rust\aeolius\src\graphics\renderervk.rs:676
   5:     0x7ff774b5c4e6 - aeoliuslib::graphics::renderervk::RendererVk::new
                        at D:\keep\hg\programs\rust\aeolius\src\graphics\renderervk.rs:195
   6:     0x7ff774aeafdd - aeolius::main
                        at D:\keep\hg\programs\rust\aeolius\src\bin\aeolius.rs:495
   7:     0x7ff774d8b821 - _rust_maybe_catch_panic
   8:     0x7ff774d871aa - std::rt::lang_start::h538f8960e7644c80
   9:     0x7ff774aefb69 - main
  10:     0x7ff774dbb4e0 - __scrt_common_main_seh
                        at f:\dd\vctools\crt\vcstartup\src\startup\exe_common.inl:253
  11:     0x7ff87f398363 - BaseThreadInitThunk
error: process didn't exit successfully: `target\debug\aeolius.exe --vulkan --debug` (exit code: 3221225477)

**Comment by StrayLightning** [comment]
Next activity would be to look through GLFW and glfw-rs sources to see what they are doing for the Vulkan initialisation, and what the difference is between Windows and Linux.  I did have a suspicion that it might require glfw.window_hint(glfw::WindowHint::ClientApi(ClientApiHint::NoApi)) on Windows, but glfw-rs doesn't seem to be set up to support that configuration.  The glfw-rs create_window method always passes through a non-null mode pointer while the GLFW documentation indicates that you should pass through null for NoApi.

**Comment by StrayLightning** [comment]
This is fixed by commit 491bc4cc60f776fcc530e9ee6bca18d9af7eb86e: The NoApi hint is required on Windows, unlike on Linux.  You must then make sure not to call make_current() on the window, which fails when you don't have a context!
